version: "3.9"

services:
  db:
    image: postgres:16-alpine   # 👈 tu versión
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: gastos_obra
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d gastos_obra"]
      interval: 5s
      retries: 5
      timeout: 5s

  backend:
    build: ./backend
    restart: always
    depends_on:
      db:
        condition: service_healthy   # 👈 espera hasta que Postgres esté listo
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
