"""init

Revision ID: d3b7b77835c2
Revises: 
Create Date: 2025-08-21 10:23:38.371088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b7b77835c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('location', sa.String(), nullable=True))
    op.add_column('proyectos', sa.Column('agua', sa.Integer(), nullable=False))
    op.add_column('proyectos', sa.Column('luz', sa.Integer(), nullable=False))
    op.add_column('proyectos', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proyectos', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proyectos', type_='foreignkey')
    op.drop_column('proyectos', 'owner_id')
    op.drop_column('proyectos', 'luz')
    op.drop_column('proyectos', 'agua')
    op.drop_column('proyectos', 'location')
    # ### end Alembic commands ###
