"""se completo crud de la clase gasto

Revision ID: e07865086ea7
Revises: 6a7396b60009
Create Date: 2025-08-21 13:37:23.178721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07865086ea7'
down_revision: Union[str, Sequence[str], None] = '6a7396b60009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('gastos', sa.Column('cantidad', sa.Float(), nullable=False))
    op.add_column('gastos', sa.Column('p_unitario', sa.Float(), nullable=False))
    op.add_column('gastos', sa.Column('p_total', sa.Float(), nullable=False))
    op.alter_column('gastos', 'proyecto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_gastos_nombre'), 'gastos', ['nombre'], unique=False)
    op.drop_column('gastos', 'monto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos', sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_gastos_nombre'), table_name='gastos')
    op.alter_column('gastos', 'proyecto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('gastos', 'p_total')
    op.drop_column('gastos', 'p_unitario')
    op.drop_column('gastos', 'cantidad')
    op.drop_column('gastos', 'nombre')
    # ### end Alembic commands ###
